### ISSUE TITLE
Allow selection of input withouth changing the input in the middle panel

### ISSUE THREAD

**Issue by adrivsh** [worldbank-climate-group/resilience-indicator-tool#37] opened 2016-08-12 16:53 UTC
Most notably clicking on the input label,

but maybe also the input value or the input distro (even if the clic does not happen exactly on the slider)

**Comment by bjohare** [comment] 2016-08-12 17:11
Duplicate of #38. Have added click handling to input label and cursor change to hand to indicate label is clickable.

**Closed as completed** 2016-08-19 12:19 UTC
